name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # The GitHub-hosted runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Action to log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub Access Token from secrets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Sets up Buildx for efficient Docker builds

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Builds and pushes the Docker image
        with:
          context: . # Build context: current directory (where Dockerfile is)
          file: ./Dockerfile # Path to your Dockerfile
          push: true # Push the image to Docker Hub
          tags: | # Define image tags
            rishikeshkesavansanmina/my-node-docker-app:latest
            rishikeshkesavansanmina/my-node-docker-app:${{ github.sha }} # Tag with the Git commit SHA for uniqueness